apiVersion: v1
kind: Service
metadata:
  name: sor-api-lb
  labels:
    app: sor-api
    role: api
spec:
  type: LoadBalancer
  selector:
    app: sor-api
    role: api
  ports:
    - name: https
      port: 443
      targetPort: 443
