apiVersion: batch/v1
kind: Job
metadata:
  name: sor-base-asset
spec:
  template:
    spec:
      containers:
      - name: sor-base-asset
        image: sebastus/dotnetapisor:test
        command: ["/bin/bash"]
        args: ["/home/scripts/Do-Work-Tf.sh", "base", "newBaseRg", "uksouth"]
        env:
        - name: AZURE_TENANT_ID
          valueFrom:
            secretKeyRef:
              name: sor-admin-secrets
              key: azure_tenant_id.txt
        - name: AZURE_APP_ID
          valueFrom:
            secretKeyRef:
              name: sor-admin-secrets
              key: azure_app_id.txt
        - name: AZURE_APP_KEY
          valueFrom:
            secretKeyRef:
              name: sor-admin-secrets
              key: azure_app_key.txt
        - name: AZURE_SUBSCRIPTION_ID
          valueFrom:
            secretKeyRef:
              name: sor-admin-secrets
              key: azure_subscription_id.txt
      restartPolicy: Never
  backoffLimit: 0
