apiVersion: batch/v1
kind: Job
metadata:
  name: sor-raw-asset
spec:
  template:
    spec:
      containers:
      - name: sor-raw-asset
        image: sebastus/dotnetapisor:test
        command: ["/bin/bash"]
        args: ["/home/scripts/Do-Work-Tf.sh", "raw", "newRawRg", "uksouth"]
        env:
        - name: AZURE_TENANT_ID
          valueFrom:
            configMapKeyRef:
              name: asset1-configmap
              key: tenant_id           
        - name: AZURE_APP_ID
          valueFrom:
            secretKeyRef:
              name: sor-admin-secrets
              key: azure_app_id.txt
        - name: AZURE_APP_KEY
          valueFrom:
            secretKeyRef:
              name: sor-admin-secrets
              key: azure_app_key.txt
        - name: AZURE_SUBSCRIPTION_ID
          valueFrom:
            configMapKeyRef:
              name: asset1-configmap
              key: subscription_id
      restartPolicy: Never
  backoffLimit: 0
