apiVersion: v1
kind: Service
metadata:
  name: sor-api-lb
  labels:
    app: sor-api
    role: api
spec:
  type: LoadBalancer
  selector:
    app: sor-api
    role: api
  ports:
    - name: http
      port: 80
      targetPort: 80
