apiVersion: batch/v1
kind: Job
metadata:
  name: sor-api
spec:
  template:
    spec:
      containers:
      - name: sor-api
        image: sebastus/dotnetapisor:v0.1.0
      restartPolicy: Never
  backoffLimit: 0
