# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

secretGenerator:
- name: sor-admin-secrets
  files:
    - "azure_app_id"
    - "azure_app_key"
    - "azure_tenant_id"
    - "azure_subscription_id"
